import{a as w,S as b,i as a}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();async function g(e,o){const r="https://pixabay.com/api/",c=new URLSearchParams({key:"44039917-a1e08adf8a4d452f4e6ec8aba",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),t=document.querySelector(".loader");t.classList.remove("is-hidden"),t.textContent="Loading images, please wait...";const{data:s}=await w.get(`${r}?${c}`);return s}function v(e){return`<li class="gallery-item" data-id="${e.id}">
        <div class="img-container" >
        <a class="large-image" href="${e.largeImageURL}">
        <img class="image" src="${e.webformatURL}" alt="${e.tags}">
        </a> 
        </div>
        <ul class="description-list" >
          <li class="description-item"><p class="description-item-text">Likes</p><p class="description-item-numb">${e.likes}</p></li>
          <li class="description-item"><p class="description-item-text">Views</p><p class="description-item-numb">${e.views}</p></li>
          <li class="description-item"><p class="description-item-text">Comments</p><p class="description-item-numb">${e.comments}</p></li>
          <li class="description-item"><p class="description-item-text">Downloads</p><p class="description-item-numb">${e.downloads}</p></li>
        </ul>
      </li>`}function f(e){return e.map(v).join("")}const S={message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",messageSize:"16px",backgroundColor:"red",position:"topRight",timeout:5e3,drag:!0,overlay:!0,overlayClose:!0},h={message:"Sorry, something goes wrong!",backgroundColor:"red",messageColor:"white",position:"topRight",timeout:5e3,drag:!0,overlay:!0,overlayClose:!0},C={message:"We're sorry, but you've reached the end of search results.",backgroundColor:"orange",messageColor:"white",position:"topRight",timeout:5e3,drag:!0,overlay:!0,overlayClose:!0},y=document.querySelector(".form"),m=document.querySelector(".images-container"),q=document.querySelector(".loader"),u=document.querySelector(".more-btn"),L=new b(".large-image",{captionDelay:250,captionsData:"alt"});y.addEventListener("submit",x);u.addEventListener("click",T);function i(e){e?u.classList.remove("is-hidden"):u.classList.add("is-hidden")}let n=1,p=0,l="";async function x(e){if(e.preventDefault(),m.innerHTML="",n=1,l=e.target.elements.query.value.trim(),l===""){a.show({message:"The field cannot be empty!",position:"topRight",backgroundColor:"red"});return}try{const o=await g(l,n);if(o.hits.length===0)a.show(S),i(!1);else{const r=f(o.hits);m.innerHTML=r,L.refresh()}q.classList.add("is-hidden"),p=Math.ceil(o.totalHits/15),p>1?i(!0):i(!1)}catch{a.show(h),i(!1)}y.reset()}async function T(){n+=1;try{const e=await g(l,n),o=f(e.hits);m.innerHTML+=o,L.refresh(),n>=p&&(i(!1),a.info(C))}catch{a.show(h)}}
//# sourceMappingURL=commonHelpers.js.map
