import{a as v,S,i as n}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&l(m)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();async function h(e,o){const a="https://pixabay.com/api/",l=new URLSearchParams({key:"44039917-a1e08adf8a4d452f4e6ec8aba",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}),t=document.querySelector(".loader");t.classList.remove("is-hidden"),t.textContent="Loading images, please wait...";const{data:s}=await v.get(`${a}?${l}`);return s}function C(e){return`<li class="gallery-item" data-id="${e.id}">
        <div class="img-container" >
        <a class="large-image" href="${e.largeImageURL}">
        <img class="image" src="${e.webformatURL}" alt="${e.tags}">
        </a> 
        </div>
        <ul class="description-list" >
          <li class="description-item"><p class="description-item-text">Likes</p><p class="description-item-numb">${e.likes}</p></li>
          <li class="description-item"><p class="description-item-text">Views</p><p class="description-item-numb">${e.views}</p></li>
          <li class="description-item"><p class="description-item-text">Comments</p><p class="description-item-numb">${e.comments}</p></li>
          <li class="description-item"><p class="description-item-text">Downloads</p><p class="description-item-numb">${e.downloads}</p></li>
        </ul>
      </li>`}function y(e){return e.map(C).join("")}const q={message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",messageSize:"16px",backgroundColor:"red",position:"topRight",timeout:5e3,drag:!0,overlay:!0,overlayClose:!0},L={message:"Sorry, something goes wrong!",backgroundColor:"red",messageColor:"white",position:"topRight",timeout:5e3,drag:!0,overlay:!0,overlayClose:!0},x={message:"We're sorry, but you've reached the end of search results.",backgroundColor:"orange",messageColor:"white",position:"topRight",timeout:5e3,drag:!0,overlay:!0,overlayClose:!0},w=document.querySelector(".form"),p=document.querySelector(".images-container"),g=document.querySelector(".loader"),f=document.querySelector(".more-btn"),b=new S(".large-image",{captionDelay:250,captionsData:"alt"});w.addEventListener("submit",T);f.addEventListener("click",$);function r(e){e?f.classList.remove("is-hidden"):f.classList.add("is-hidden")}function d(e){e?g.classList.remove("is-hidden"):g.classList.add("is-hidden")}let i=1,u=0,c="";async function T(e){if(e.preventDefault(),p.innerHTML="",i=1,c=e.target.elements.query.value.trim(),c===""){n.show({message:"The field cannot be empty!",position:"topRight",backgroundColor:"red"});return}d(!0);try{const o=await h(c,i);if(o.hits.length===0)n.show(q),r(!1);else{const a=y(o.hits);p.innerHTML=a,b.refresh()}u=Math.ceil(o.totalHits/15),u>1?r(!0):r(!1)}catch{n.show(L),r(!1)}finally{d(!1)}w.reset()}async function $(){i+=1,d(!0);try{const e=await h(c,i),o=y(e.hits);p.innerHTML+=o,b.refresh(),i>=u&&(r(!1),n.info(x))}catch{n.show(L)}finally{d(!1),i<u&&r(!0)}}
//# sourceMappingURL=commonHelpers.js.map
